name: Peter McClory
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15318
title: 'Illustration, drawings and portrait art in Cheshire and Manchester'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77459478-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9dcba'
    - '#cbbc9b'
    - '#1b1a15'
    - '#908363'
    - '#36362a'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
