name: Peter McClory
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15318
title: 'Illustration, drawings and portrait art in Cheshire and Manchester'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77459478-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefdf8'
    - '#dbdbd1'
    - '#000000'
    - '#484742'
    - '#8f8f87'
  brandStrength: 0.375
  lightness: 0.9266018066555262
  saturation: 0.49530106084421277
  rhythmicContrast: 0.5192084764130414
purpose: []
