name: Peter McClory
favicon: null
layout_spectrum: 0.4604300258215517
typography_spectrum: 0.510886721778661
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.28434943384490907
  lightness: 0.9266018066555262
  saturation: 0.49530106084421277
  rhythmicContrast: 0.5192084764130414
purpose: []
